import = [
    # "/home/gyk/.config/alacritty/colors/myblue.toml"
    "/home/gyk/.config/alacritty/colors/monokai.toml"
    # "/home/gyk/.config/alacritty/colors/tokyonight_storm.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "0xProto Nerd Font"
style = "Bold"

[font.bold_italic]
family = "0xProto Nerd Font"
style = "Bold Italic"

[font.italic]
family = "0xProto Nerd Font"
style = "Italic"

[font.normal]
family = "0xProto Nerd Font"
style = "Regular"

[window]
startup_mode = "Maximized"
title = "Alacritty"

